baseURL = "https://accidentallycoded.com/"
languageCode = "en-us"
title = "accidentallycoded.com"
theme = "hi"


pygmentsStyle = "solarized-dark256"
pygmentsCodeFences = true

[build]
writeStats = true
